### ISSUE TITLE
Hardcoded GitHub URL

### ISSUE THREAD

**Issue by benemon** [openshiftio/booster-catalog-service#7] opened 2017-08-17 10:50 UTC
When deploying the launchpad templates on-prem, sometimes a user doesn't have connectivity to GitHub. As a consequence, all boosters are cloned and hosted on internal git repo. 

It would be good if the GITHUB_URL in GitBoosterCatalogPathProvider could be externalised into an environment variable so it can be repointed at hosted Git repositories.

For example:

``
   /**
    * @param catalogRepositoryURI
    * @param catalogRef
    */
   public GitBoosterCatalogPathProvider(String catalogRepositoryURI, String catalogRef, Path rootDir)
   {
      super();
      this.gitRepositoryURL = System.getenv("GIT_BOOSTER_REPOSITORY_URL") != null ? System.getenv("GIT_BOOSTER_REPOSITORY_URL") : GITHUB_URL;
      this.catalogRepositoryURI = catalogRepositoryURI;
      this.catalogRef = catalogRef;
      this.rootDir = rootDir;
   }

``

**Comment by gastaldi** [comment] 2017-08-17 10:55
That is how consumers of this library do when in conjunction with the Builder class. See https://github.com/openshiftio/launchpad-addon/blob/master/src/main/java/io/openshift/launchpad/BoosterCatalogServiceProducer.java

I really don't think that introducing a magical env variable here would be the solution

**Comment by gastaldi** [comment] 2017-08-17 11:01
You can also specify a different CatalogPathProvider implementation in your Builder, so perhaps that makes more sense instead. (Eg. Have an impl that fallbacks to the local git if Github is unavailable)

**Comment by benemon** [comment] 2017-08-17 11:24
To me, the first approach you list would be more palatable - as someone deploying the launchpad template on-prem, setting an ENV VAR or System Property is much more flexible than creating a new CatalogPathProvider - although I agree that magic variables are bad. We already do it for the Booster Catalog location, so why not for the Boosters themselves?

Fundamentally, there's nothing wrong with what the GitBoosterCatalogPathProvider is doing, and from looking at the source there doesn't seem to be anything which ties the code to a particular Git implementation. So we're just talking about building in flexibility to point to different Git services, and probably defaulting to Github if no alternative is configured.

**Comment by gastaldi** [comment] 2017-08-17 11:30
Right, you can use the GitBoosterCatalogPathProvider for any Git repository you want, but changing its state in the constructor for different values sounds bad, specially when talking about a test perspective (eg. You write a test for it and then don't realize that it fails because some env var is set).

So unless I'm convinced otherwise, I'd rather keep having the consumer of this library decide which provider with their specific parameters to use :)

**Comment by benemon** [comment] 2017-08-17 11:48
Fair enough - but that means that the GitBoosterCatalogPathProvider should still have some capability to override the hardcoded GITHUB_URL value without unnecessarily creating a new provider class - or having to rebuild it with a new hardcoded value :)

Does that make sense? I kind of get the impression we may be talking ourselves round in circles a bit.

**Comment by gastaldi** [comment] 2017-08-17 11:58
Well, that's the point I don't fully agree. Since that sounds like a business requirement, I'd like to keep the GitBoosterCatalogPathProvider impl as is (deal with a single repository) and introduce a new impl that may act as a circuit breaker. 

That IMHO would prevent unexpected behavior in tests and would allow each consumer of this library to decide how to handle it and decide how to fetch the values (what if you got multiple catalogs to be indexed in the same process?).

Kinda like Occam's razor (simplest answer is often correct) ;)

**Comment by gastaldi** [comment] 2017-08-17 12:07
Probably a new impl would not even be necessary if the git repository to use is specified in the Builder

**Comment by benemon** [comment] 2017-08-17 12:10
Yes, I was actually just looking at that. Even if you didn't specify anything in the builder, you could default to the settings you have now, and that wouldn't be a test-breaking change.

**Comment by gastaldi** [comment] 2017-08-17 12:10
My point is that this env variable reading could happen, but in the classes that use the Builder, not inside this class implementation.

Does that make sense?

**Comment by gastaldi** [comment] 2017-08-17 12:13
Like in https://github.com/openshiftio/booster-catalog-service/blob/master/src/test/java/io/openshift/booster/catalog/BoosterCatalogServiceTest.java#L28

**Comment by benemon** [comment] 2017-08-17 12:16
Yup, perfectly. I like that because it gives you flexibility whilst protecting the Provider implementations.

**Comment by gastaldi** [comment] 2017-08-17 12:18
Awesome, thank you for understanding my point of view. Can this issue be closed now?

**Comment by benemon** [comment] 2017-08-17 12:19
Yes absolutely. Thank you for the exchange and insight!

**Comment by gastaldi** [comment] 2017-08-17 12:22
My pleasure. Closing now

**Closed by gastaldi** 2017-08-17 12:22 UTC
